-- MySQL Script generated by MySQL Workbench
-- 2017年05月27日 星期六 18时18分15秒
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema believe_user
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `believe_user` ;

-- -----------------------------------------------------
-- Schema believe_user
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `believe_user` DEFAULT CHARACTER SET utf8 ;
USE `believe_user` ;

-- -----------------------------------------------------
-- Table `believe_user`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `believe_user`.`user` ;

CREATE TABLE IF NOT EXISTS `believe_user`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `account` VARCHAR(45) NOT NULL,
  `cellphone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(255) NOT NULL,
  `nickname` VARCHAR(45) NULL,
  `identity` VARCHAR(45) NOT NULL,
  `roles` VARCHAR(45) NOT NULL,
  `headimage` VARCHAR(45) NULL,
  `status` VARCHAR(45) NULL,
  `babyid` VARCHAR(45) NULL,
  `sex` INT NOT NULL,
  `age` VARCHAR(45) NULL,
  `realname` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '用户信息表\n';


-- -----------------------------------------------------
-- Table `believe_user`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `believe_user`.`roles` ;

CREATE TABLE IF NOT EXISTS `believe_user`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(45) NOT NULL,
  `descriotion` VARCHAR(45) NULL,
  `permission_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '角色表';


-- -----------------------------------------------------
-- Table `believe_user`.`baby`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `believe_user`.`baby` ;

CREATE TABLE IF NOT EXISTS `believe_user`.`baby` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `baby_name` VARCHAR(45) NOT NULL,
  `baby_age` INT NULL,
  `baby_sex` INT NULL,
  `baby_nickName` VARCHAR(45) NULL,
  `baby_headimage` VARCHAR(45) NULL,
  `photo` JSON NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '宝宝信息表';


-- -----------------------------------------------------
-- Table `believe_user`.`permission`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `believe_user`.`permission` ;

CREATE TABLE IF NOT EXISTS `believe_user`.`permission` (
  `id` INT NOT NULL,
  `parent_id` INT NOT NULL DEFAULT 0,
  `name` VARCHAR(45) NOT NULL,
  `descriotion` VARCHAR(45) NULL,
  `status` VARCHAR(45) NOT NULL COMMENT '是否生效\n',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = '权限列表\n';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
